### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by jboynes** [SignalK/signalk-server-java#11] opened 2015-12-05 18:48 UTC
Trying to build 959c8d0cee08ae3599f257fdbbd4591985857ded I am getting failures from the following tests:
- `JsonSubscribeProcessorTest#shouldUnSubscribeOne`
- `FullExportProcessorTest#shouldCreateInstantDelta`
- `GetSignalkKeysTest#printKeys`

I noticed cd0952244c9ac295b39d6b99ccdcf9a2cc705956 mentions two unreliable tests - are the those the first two above?

`printKeys` fails because of a hard coded reference to `/home/robert/gitrep` which I can patch but I don't see what that test is actually asserting. Is the output used somehow or can this be deleted/ignored/converted to a command utility?

**Comment by rob42** [comment] 2015-12-05 20:14
Yes they work normally when run individually, but fail in the maven build. I cant find the cause - presumably some sort of dirty context from other tests?
The last one (GetSignalkKeysTest#printKeys) is used to generate SignalkConstants lines from the current specification jsonschema. It should be marked @Ignore 

I have a big commit to do today, which will fix some of the above.

**Comment by rob42** [comment] 2016-01-27 09:30
Fixed now, so closing this

**Comment by jboynes** [comment] 2016-01-28 17:04
These are still failing for me:

```
Failed tests:   shouldCreateInstantDelta(nz.co.fortytwo.signalk.processor.FullExportProcessorTest): 1:MapSizeAfter != queue size expected:<0> but was:<1>
  shouldUnSubscribeOne(nz.co.fortytwo.signalk.processor.JsonSubscribeProcessorTest): expected:<2> but was:<3>
```

**Comment by rob42** [comment] 2016-01-28 19:14
Yes me too - immediately after I closed this :-(

**Comment by jboynes** [comment] 2016-01-29 15:19
Two PR's for this:
#20 to fix FullExportProcessor
#21 to fix JsonSubscribeProcessorTest

**Comment by rob42** [comment] 2016-06-29 22:14
Closing, all tests working reliably now

**Closed as completed by rob42** 2016-06-29 22:14 UTC
